config/routes.rb
Refinery::Core::Engine.routes.prepend do

  devise_for :clients,  :class_name => "Refinery::Clients::Client",
                                :controllers => {:sessions => 'refinery/clients/sessions', :passwords => 'refinery/clients/passwords', :registrations => 'refinery/clients/registrations', :confirmations => 'refinery/clients/confirmations'}

  devise_scope :client do
      get "/clients/change_psw", :to => "clients/registrations#edit_password", :as => :edit_password
      match 'raptcha(/:action)', to: 'clients/registrations#raptcha_generate'
  end

  get "/clients/office", :to => "clients/office#index", :as => :office

  namespace :clients do
    resources :ships, controller: 'ships'
    match 'uploadfile', to: 'upload#create_file', :as => :uploadfile, via: [:post]
    match 'uploadphoto', to: 'upload#create_photo', :as => :uploadphoto, via: [:post]
    match 'deletefile', to: 'upload#delete_file', :as => :deletefile, via: [:post]
    match 'deletephoto', to: 'upload#delete_photo', :as => :deletephoto, via: [:post]

    match 'subscribed', to: 'subscribe#subscribed', :as => :subscribed, via: [:post]
    match 'unsubscribed', to: 'subscribe#unsubscribed', :as => :unsubscribed, via: [:post]
  end
  match 'sendnewsmail/:id', to: 'news/items#send_news_to_subscribers', :as => :sendnewsmail

end

Refinery::Ships::Engine.routes.prepend do
  devise_for :clients,  :class_name => "Refinery::Clients::Client",
                                :controllers => {:office => 'refinery/clients/office', :sessions => 'refinery/clients/sessions', :passwords => 'refinery/clients/passwords', :registrations => 'refinery/clients/registrations', :confirmations => 'refinery/clients/confirmations'}
  devise_scope :client do
      get "/clients/office", :to => "clients/office#index", :as => :office
  end

  namespace :clients do
    resources :ships, controller: 'ships'
    match 'uploadfile', to: 'upload#create_file', :as => :uploadfile, via: [:post]
    match 'uploadphoto', to: 'upload#create_photo', :as => :uploadphoto, via: [:post]
    match 'deletefile', to: 'upload#delete_file', :as => :deletefile, via: [:post]
    match 'deletephoto', to: 'upload#delete_photo', :as => :deletephoto, via: [:post]
  end
end

Refinery::Inquiries::Engine.routes.prepend do
  devise_for :clients,  :class_name => "Refinery::Clients::Client",
                                :controllers => {:office => 'refinery/clients/office', :sessions => 'refinery/clients/sessions', :passwords => 'refinery/clients/passwords', :registrations => 'refinery/clients/registrations', :confirmations => 'refinery/clients/confirmations'}
  devise_scope :client do
      get "/clients/office", :to => "clients/office#index", :as => :office
  end
end

Refinery::News::Engine.routes.prepend do
  devise_for :clients,  :class_name => "Refinery::Clients::Client",
                                :controllers => {:office => 'refinery/clients/office', :sessions => 'refinery/clients/sessions', :passwords => 'refinery/clients/passwords', :registrations => 'refinery/clients/registrations', :confirmations => 'refinery/clients/confirmations'}
  devise_scope :client do
      get "/clients/office", :to => "clients/office#index", :as => :office
  end
end

Marinerus::Application.routes.draw do

  mount Refinery::Core::Engine, :at => '/'

end

app/models/refinery/clients/client.rb
#require 'active_record'
require 'devise'

module Refinery
  module Clients
    class Client < Refinery::Core::BaseModel
      self.table_name = 'refinery_clients'

      has_many :ships, :class_name => 'Refinery::Ships::Ship'
      has_many :attachments, :class_name => 'Refinery::Ships::Attachment'

      acts_as_indexed :fields => [:name]

     # validates :email, :presence => true, :uniqueness => true

      #devise methods
      # Include default devise modules. Others available are:
	# :token_authenticatable, :confirmable,
	# :lockable, :timeoutable and :omniauthable
      #attr_accessor :login
      devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :confirmable, :authentication_keys => [:email]

	# Setup accessible (or protected) attributes for your model
	attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :company, :job, :phone, :mail_me

    end
  end
end

app/controllers/refinery/clients/confirmations_controller.rb
module Refinery
  module Clients
    class ConfirmationsController < Devise::ConfirmationsController
      helper Refinery::Core::Engine.helpers
      # layout 'refinery/clients/layouts/login'
      # GET /resource/confirmation/new
      def new
        build_resource({})
      end

      # POST /resource/confirmation
      def create
        self.resource = resource_class.send_confirmation_instructions(resource_params)

        if successfully_sent?(resource)
          respond_with({}, :location => after_resending_confirmation_instructions_path_for(resource_name))
        else
          respond_with(resource)
        end
      end

      # GET /resource/confirmation?confirmation_token=abcdef
      def show
        self.resource = resource_class.confirm_by_token(params[:confirmation_token])

        if resource.errors.empty?
          logger.debug(resource)
          logger.debug(resource_name)
          set_flash_message(:notice, :confirmed) if is_navigational_format?
          # respond_with_navigational(resource){ redirect_to after_confirmation_path_for(resource_name, resource) }
          redirect_to office_path if sign_in(resource_name, resource)
          # all my stupied tries next:
          # respond_with_navigational(resource){ redirect_to office_path }
          # respond_with resource, :location => after_sign_in_path_for(resource)
        else
          respond_with_navigational(resource.errors, :status => :unprocessable_entity){ render :new }
        end
      end

      protected

        # The path used after resending confirmation instructions.
        def after_resending_confirmation_instructions_path_for(resource_name)
          new_session_path(resource_name) if is_navigational_format?
        end

        # The path used after confirmation.
        def after_confirmation_path_for(resource_name, resource)
          after_sign_in_path_for(resource)
        end
      
    end
  end
end

app/controllers/refinery/clients/office_controller.rb
module Refinery
  module Clients
    class OfficeController < ::ApplicationController
        layout 'refinery/clients/layouts/login'
        #before_filter :check, :only=>[:create]
        # crudify   :'refinery/ships/ship', 
            # :xhr_paging => true

        #before_filter :all_collections, :only=>[:new, :edit]

        def index
            if client_signed_in?
                @ships = Refinery::Ships::Ship.includes(:translations, :page_status).where(:client_id=>current_client.id).order('updated_at DESC')
                @all = @ships
                @moderate = @ships.select{|ship| ship.page_status.id == 1}
                @published = @ships.select{|ship| ship.page_status.id == 2}
                if (params[:status]=='1' or params[:status]=='2')
                    params[:status]=='1' ? @ships = @moderate : @ships = @published
                end
            else
                 redirect_to(root_path)
            end
        end
        

        protected
        def all_collections
            @categories = Refinery::Categories::Category.all
            #@clients

            @page_statuss = PageStatus.all
            @statuss = Status.all
            @areas = Area.all
            @choices = Choice.all
            @conditions = Condition.all
            @currencies = Currency.all
            @enginetypes = Enginetype.all
            @fuels = Fuel.all
            @gmdsss = Gmdss.all
            @hullmaterials = Hullmaterial.all
            @hulltypes = Hulltype.all
            @powers = Power.all
            @propulsions = Propulsion.all
            @registrations = Registration.all
            @registrs = Registr.all
            @speeds = Speedname.all
            @vats = Vat.all
        end

    end
  end
end

app/controllers/refinery/clients/passwords_controller.rb
module Refinery
  module Clients
    class PasswordsController < Devise::PasswordsController
    	layout 'refinery/clients/layouts/login'
    	# prepend_before_filter :log, :only => :update

    	  def edit
	    self.resource = resource_class.new
	    resource.reset_password_token = params[:reset_password_token]
	  end

	  # PUT /resource/password
	  def update
	    self.resource = resource_class.reset_password_by_token(resource_params)

	    if resource.errors.empty?
	      resource.unlock_access! if unlockable?(resource)
	      flash_message = resource.active_for_authentication? ? :updated : :updated_not_active
	      set_flash_message(:notice, flash_message) if is_navigational_format?
	      sign_in(resource_name, resource)
	      respond_with resource, :location => after_resetting_password_path_for(resource)
	    else
	      respond_with resource
	    end
	  end


	  protected
		def after_sending_reset_password_instructions_path_for(resource_name)
			office_path
		end
		def after_resetting_password_path_for(resource)
			office_path
		end
    end
  end
end

app/controllers/refinery/clients/sessions_controller.rb
module Refinery
  module Clients
    class SessionsController < Devise::SessionsController
    	layout 'refinery/clients/layouts/login'
    	#before_filter :check, :only=>[:create]

	def create
     		client = Client.find_by_email(params[:client][:email])
		if client.present? and client.valid_password?(params[:client][:password])
			self.resource = client
		else
			self.resource = warden.authenticate!(auth_options)
		end
		set_flash_message(:notice, :signed_in) if is_navigational_format?
		sign_in(resource_name, resource)
		respond_with resource, :location => after_sign_in_path_for(resource)
	end

      def create_default
        self.resource = warden.authenticate!(auth_options)
        set_flash_message(:notice, :signed_in) if is_navigational_format?
        sign_in(resource_name, resource)
        respond_with resource, :location => after_sign_in_path_for(resource)
      end

    	protected
    	def after_sign_in_path_for(resource_or_scope)
    		refinery.root_path
    	end
    	# def after_sign_out_path_for(resource_or_scope)
    	# 	refinery.root_path
    	# end

    # 	def auth_options
    #   { :default_scope => :client, :default_strategies => :client}
    # end

    def check
    	#request.env["devise.skip_timeout"] = true 
    	request.env["authentication_keys"] = [:email]

    	logger.debug("//////////////////////////////////////////////////////////")
    	logger.debug(">request.env:  #{lambda{request.env.each do |t| return t end}.call}")
    	logger.debug("//////////////////////////////////////////////////////////")
    	logger.debug(">>>>>>>>>>>>>>>>>>devise.skip_timeout:   #{request.env["devise.skip_timeout"]} >>class: devise.skip_timeout:   #{request.env.class}")
    	logger.debug(">>>>>>>>>>>>>>>>>>warden:   #{warden}>>class:   #{warden.class}")
    	logger.debug(">>>>>>>>>>>>>>>>>>warden:   #{request.env["authentication_keys"]}")
    	logger.debug(">>>>>>>>>>>>>>>>>>warden:   #{request.env["request_keys"]}")

    end
    	
    end
  end
end

app/controllers/refinery/clients/ships_controller.rb
module Refinery
  module Clients
    class ShipsController < ::ApplicationController #< ::ActionController::Base
      #include ::Refinery::ApplicationController
      #helper ApplicationHelper
      #helper Refinery::Core::Engine.helpers
      #include Refinery::Admin::BaseController
      layout 'refinery/clients/layouts/login'


    	before_filter :client?, except: :new
    	before_filter :add_new_client?, only: :new

      crudify	:'refinery/ships/ship',
      			:xhr_paging => true

      before_filter	:all_collections, :only=>[:new, :edit, :create, :update]
      before_filter	:new_attach_init, :only=>[:new]
      before_filter	:edit_attach_init, :only=>[:edit, :update]
      before_filter	:create_attach_init, :only=>[:create]
      # before_filter	:attach_update, :only=>[:create, :update]

      def new
        @ship = Refinery::Ships::Ship.new(:client_id=>current_client.id)
      end

      def create
      	@attach = Refinery::Ships::Attachment.where({client_id: current_client.id, ship_id: nil}).first
		if (@ship = Refinery::Ships::Ship.create(params[:ship]){|s| s.client_id = current_client.id}).valid?  #do |s| s.client_id = current_client.id end).valid?
			flash.notice = t(
			'refinery.crudify.created',
			:what => "#{@ship.title}'"
			)

                    attach_update
                    ::Refinery::Inquiries::InquiryMailer.order_notification(@ship).deliver
			redirect_to office_path
		else
			create_or_update_unsuccessful 'new'
		end
      end

      # def edit
      #   # object gets found by find_#{singular_name} function
      #   @attach = Refinery::Ships::Attachment.where(ship_id: @ship.id).first
      # end

      def update
	      if @ship.update_attributes(params[:ship])
			#attach_update
			redirect_to office_path
		else
			create_or_update_unsuccessful 'edit'
	      end
      end

      def destroy
		if @ship.destroy
			redirect_to office_path
		end
      end
#####################################----Set locale----#############################################################################
      def find_or_set_locale
        if (params[:set_locale] and ::Refinery::I18n.locales.keys.map(&:to_sym).include?(params[:set_locale].to_sym))
          ::Refinery::I18n.current_locale = params[:set_locale].to_sym
          redirect_back_or_default(refinery.admin_root_path) and return
        else
          ::I18n.locale = ::Refinery::I18n.current_locale
        end
      end

      def globalize!
        if ::Refinery::I18n.frontend_locales.any?
          if params[:switch_locale]
            Thread.current[:globalize_locale] = params[:switch_locale].to_sym
          elsif ::I18n.locale != ::Refinery::I18n.default_frontend_locale
            Thread.current[:globalize_locale] = ::Refinery::I18n.default_frontend_locale
          end
        end

        Thread.current[:globalize_locale] = ::I18n.locale if Thread.current[:globalize_locale].nil?
      end
      # globalize! should be prepended first so that it runs after find_or_set_locale
      prepend_before_filter :globalize!, :find_or_set_locale
      protected :globalize!, :find_or_set_locale
###################################################################################################################################
      protected
      def client?
      		redirect_to root_path if !client_signed_in?
      end
      def add_new_client?
      		redirect_to new_client_registration_path if !client_signed_in?
      end
      def all_collections
        @categories = Refinery::Categories::Category.all
        #@clients

        @page_statuss = Refinery::Ships::PageStatus.all
        @statuss = Refinery::Ships::Status.all
        @areas = Refinery::Ships::Area.all
        @choices = Refinery::Ships::Choice.all
        @conditions = Refinery::Ships::Condition.all
        @currencies = Refinery::Ships::Currency.all
        @enginetypes = Refinery::Ships::Enginetype.all
        @fuels = Refinery::Ships::Fuel.all
        @gmdsss = Refinery::Ships::Gmdss.all
        @hullmaterials = Refinery::Ships::Hullmaterial.all
        @hulltypes = Refinery::Ships::Hulltype.all
        @powers = Refinery::Ships::Power.all
        @propulsions = Refinery::Ships::Propulsion.all
        @registrations = Refinery::Ships::Registration.all
        @registrs = Refinery::Ships::Registr.all
        @speeds = Refinery::Ships::Speedname.all
        @fuelnames = Refinery::Ships::Fuelname.all
        @vats = Refinery::Ships::Vat.all
      end

      def new_attach_init
	      	if @attach = Refinery::Ships::Attachment.where({client_id: current_client.id, ship_id: nil}).first
	      		@attach.photos.each {|e| e.destroy} if @attach.photos.any? 
	      		@attach.docs.each {|e| e.destroy} if @attach.docs.any?
	      		@attach.reload
	      	else
	      		@attach = Refinery::Ships::Attachment.create(client_id: current_client.id)
	      	end
	      	@fileholder = Refinery::Ships::Doc.new
      		@photoholder = Refinery::Ships::Photo.new
      end
      
      def edit_attach_init
    		@attach = Refinery::Ships::Attachment.where(ship_id: @ship.id).first
    		#@attach = Refinery::Ships::Attachment.where({client_id: current_client.id, ship_id: params[:id]}).first
    		@fileholder = Refinery::Ships::Doc.new
    		@photoholder = Refinery::Ships::Photo.new
    	end

    	def create_attach_init
    		@attach = Refinery::Ships::Attachment.where({client_id: current_client.id, ship_id: nil}).first
    		@fileholder = Refinery::Ships::Doc.new
    		@photoholder = Refinery::Ships::Photo.new
    	end

      def attach_update
    		@attach.update_attributes(ship_id: @ship.id)
      end
    end
  end
end

app/controllers/refinery/clients/upload_controller.rb
module Refinery
	module Clients
		class UploadController < ::ApplicationController#::ActionController::Base 

			def create_file
				@fileholder = Refinery::Ships::Doc.create(params[:doc])
			end

			def create_photo
				@photoholder = Refinery::Ships::Photo.create(params[:photo])
			end

			def delete_photo
				@id = params[:id]
				@photoholder = Refinery::Ships::Photo.find(params[:id])
				@photoholder.photo = nil
				@photoholder.destroy

				render :text => "Deleted #{params[:id]}"
			end

			def delete_file
				@id = params[:id]
				@fileholder = Refinery::Ships::Doc.find(params[:id])
				@fileholder.doc = nil
				@fileholder.destroy

				render :text => "Deleted #{params[:id]}"
			end
		end
	end
end

app/views/refinery/pages/about.html.erb
<%= render '/refinery/draft_page_message' unless @page.try(:live?) -%>
<%#= render '/refinery/content_page' %>
<div class="one_column">
	<%= render partial:  Globalize.locale.to_s=="ru" ? "/refinery/about_ru" : "/refinery/about_en" %>
</div>

app/views/refinery/pages/demand.html.erb
<% Globalize.locale.to_s=="ru" ? is_ru=true : is_ru=false %>

<%= render '/refinery/draft_page_message' unless @page.try(:live?) -%>
<%#= render '/refinery/content_page' %>
<div class="wrap">
	<div id="container">
		<div class="positions">
			<div id="positions<%= "_e" if !is_ru %>"></div>
			<ul class="list_positions">
				<li class="odd first"><%= link_to is_ru ? "Показать всё" : "All", refinery.ships_ships_path %> [<%= @all.size %>]</li>
				<%= render partial: "/refinery/category", collection: @categories %>
			</ul>
			<% if session[:httpSuccess] %>
			<div id="cur_lable"><%= is_ru ? "Курс валют" : "Currency"%></div>
			<div id="currency">
				<div id="cur_head"><%= session[:usd].last["Date"] %></div>
				<ul>
					<li>USD&nbsp;&nbsp;<%= session[:usd].last["Value"].gsub(",", ".").to_f.round(2) %>&nbsp;<%= (session[:usd][-1]["Value"].gsub(",", ".").to_f-session[:usd][-2]["Value"].gsub(",", ".").to_f)>0 ? image_tag("up-arrow.png") : image_tag("down-arrow.png") %></li>
					<li>EUR&nbsp;&nbsp;<%= session[:euro].last["Value"].gsub(",", ".").to_f.round(2) %>&nbsp;<%= (session[:euro][-1]["Value"].gsub(",", ".").to_f-session[:euro][-2]["Value"].gsub(",", ".").to_f)>0 ? image_tag("up-arrow.png") : image_tag("down-arrow.png") %></li>
					<li>GBP&nbsp;&nbsp;<%= session[:gbp].last["Value"].gsub(",", ".").to_f.round(2) %>&nbsp;<%= (session[:gbp][-1]["Value"].gsub(",", ".").to_f-session[:gbp][-2]["Value"].gsub(",", ".").to_f)>0 ? image_tag("up-arrow.png") : image_tag("down-arrow.png") %></li>
				</ul>
			</div>
			<% end %> <!-- End of httpSuccess checking (is CBR responsible?..)  -->
		</div>
		<div class="content_container_sm">
			<span class="h2_"><%= is_ru ? "Запросы" : "Demands" %></span>
			<table class="ship_table_common<%= "_e" if !is_ru %> compact row-border hover" cellspacing="0" width="100%">
			  <thead>
			    <tr>
			      <th class="dt-head-center"><%= is_ru ? "Лот №" : "ID" %></th>
			      <th><%= is_ru ? "Обновлён" : "Updated" %></th>
			      <th><%= is_ru ? "Тип" : "Category" %></th>
			      <th><%= is_ru ? "Описание" : "Description" %></th>
			      <th><%= is_ru ? "Место" : "Location" %></th>
			      <th><%= is_ru ? "Год" : "Year" %></th>
			      <th></th>
			    </tr>
			  </thead>

			  <tbody>
			    <%= render partial: "refinery/ships/ships/ship", collection: @demands_ships %>
			  </tbody>
			</table>

		</div>
		
		<!-- <div class="clear">&nbsp;</div> -->
		<div class="right-column">
			<%= render "/refinery/adds", collection: @categories %>
		</div>
	</div>
</div>

<div class="popup_container"></div>	<!-- invisible popup -->




    

app/views/refinery/pages/home.html.erb
<% Globalize.locale.to_s=="ru" ? is_ru=true : is_ru=false %>

<%= render '/refinery/draft_page_message' unless @page.try(:live?) -%>
<%#= render '/refinery/content_page' %>
<div class="wrap">
	<div id="container">
		<div class="positions">
			<div id="positions<%= "_e" if !is_ru %>"></div>
			<ul class="list_positions">
				<li class="odd first"><%= link_to is_ru ? "Показать всё" : "All", refinery.ships_ships_path %> [<%= @all.size %>]</li>
				<%= render partial: "/refinery/category", collection: @categories %>
			</ul>
			<% if session[:httpSuccess] %>
			<div id="cur_lable"><%= is_ru ? "Курс валют" : "Currency"%></div>
			<div id="currency">
				<div id="cur_head"><%= session[:usd].last["Date"] %></div>
				<ul>
					<li>USD&nbsp;&nbsp;<%= session[:usd].last["Value"].gsub(",", ".").to_f.round(2) %>&nbsp;<%= (session[:usd][-1]["Value"].gsub(",", ".").to_f-session[:usd][-2]["Value"].gsub(",", ".").to_f)>0 ? image_tag("up-arrow.png") : image_tag("down-arrow.png") %></li>
					<li>EUR&nbsp;&nbsp;<%= session[:euro].last["Value"].gsub(",", ".").to_f.round(2) %>&nbsp;<%= (session[:euro][-1]["Value"].gsub(",", ".").to_f-session[:euro][-2]["Value"].gsub(",", ".").to_f)>0 ? image_tag("up-arrow.png") : image_tag("down-arrow.png") %></li>
					<li>GBP&nbsp;&nbsp;<%= session[:gbp].last["Value"].gsub(",", ".").to_f.round(2) %>&nbsp;<%= (session[:gbp][-1]["Value"].gsub(",", ".").to_f-session[:gbp][-2]["Value"].gsub(",", ".").to_f)>0 ? image_tag("up-arrow.png") : image_tag("down-arrow.png") %></li>
				</ul>
			</div>
			<% end %> <!-- End of httpSuccess checking (is CBR responsible?..)  -->
		</div>
		<div class="content_container_sm">
			<%= form_for(@search, url: refinery.ships_ships_path, method: 'get') do |f| %>
			<div id="short_search">
				<div class="left">
					<div>
						<%= is_ru ? "Описание:" : "Description:" %><br />
						<%= f.text_field(:info) %>
					</div>
				</div>
				<div class="center">
					<%= f.submit("", type: 'image', src: asset_path(is_ru ? 'search_btn.png' : 'search_btn_e.png')) %><br />
					<%= link_to is_ru ? "Расширенный поиск" : "Advanced search", refinery.ships_ships_path, style: "color:#2c87af;" %>
				</div>
				<div class="right">
					<div class="right_top"><span><%= link_to is_ru ? "Отправить запрос" : "Demand", refinery.inquiries_new_inquiry_path %></span></div>
					<div><span><%= link_to is_ru ? "Отправить предложение" : "Add new", new_clients_ship_path %></span></div>
				</div>
			</div>
			<% end %>
			<% if @recomended.any? %>
			<span class="h2"><%= is_ru ? "Рекомендуем обратить внимание" : "Recomended" %></span>
			<div id="recomended">
			<% @recomended.each do |e| %>
				<%= link_to(refinery.ships_ship_path(e), title: e.info) do %>
				<div class="recomended">
					<div class="pic_container">
						<div class="pic">
							<% if e.attachment.photos.any? %>
								<%= image_tag(asset_path(e.attachment.photos.first.photo.url(:main)), width: "130px") %>
							<% else %>
								<%= image_tag(asset_path("no_foto.png"), width: "130px") %>
							<% end %>
						</div>
						<span class="lot_label"><%= is_ru ? "Лот №" : "ID №" %>	<%= e.id %></span>
					</div>
					<div class="pic_label">
						<%= is_ru ? e.category.rutitle : e.category.entitle %>
					</div>
				</div>
				<% end %>
			<% end %>
			</div>
			<% end %>

			<span class="h2"><%= is_ru ? "Последние предложения" : "Last offers" %></span>
			<table class="ship_table_last_adds<%= "_e" if !is_ru %> compact row-border hover" cellspacing="0" width="100%">
			  <thead>
			    <tr>
			      <th class="dt-head-center"><%= is_ru ? "Лот №" : "ID" %></th>
			      <th><%= is_ru ? "Обновлён" : "Updated" %></th>
			      <th><%= is_ru ? "Тип" : "Category" %></th>
			      <th><%= is_ru ? "Описание" : "Description" %></th>
			      <th><%= is_ru ? "Место" : "Location" %></th>
			      <th><%= is_ru ? "Год" : "Year" %></th>
			      <th></th>
			    </tr>
			  </thead>

			  <tbody>
			    <%= render partial: "refinery/ships/ships/ship", collection: @last_ships.limit(10) %>
			  </tbody>
			</table>

			<% if @demands_ships.any? %>
			<span class="h2"><%= is_ru ? "Последние запросы" : "Last demands" %></span>
			<table class="ship_table_last_demands<%= "_e" if !is_ru %> compact row-border hover" cellspacing="0" width="100%">
			  <thead>
			    <tr>
			      <th class="dt-head-center"><%= is_ru ? "Лот №" : "ID" %></th>
			      <th><%= is_ru ? "Обновлён" : "Updated" %></th>
			      <th><%= is_ru ? "Тип" : "Category" %></th>
			      <th><%= is_ru ? "Описание" : "Description" %></th>
			      <th><%= is_ru ? "Место" : "Location" %></th>
			      <th><%= is_ru ? "Год" : "Year" %></th>
			      <th></th>
			    </tr>
			  </thead>

			  <tbody>
			    <%= render partial: "refinery/ships/ships/ship", collection: @demands_ships.limit(10) %>
			  </tbody>
			</table>
			<% end %>


		</div>
		
		<!-- <div class="clear">&nbsp;</div> -->
		<div class="right-column">
			<%= render "/refinery/adds", collection: @categories %>
		</div>
	</div>
</div>

<div class="popup_container"></div>	<!-- invisible popup -->




    

app/views/refinery/pages/show.html.erb
<div class="wrap">
	<div id="container">
		<div class="content_container_big">
			<%= render "/refinery/content_page" %>
		</div>
		<div class="right-column">
			<%#= render "/refinery/adds", collection: @categories %>
		</div>
	</div>
</div>