config/routes.rb
Refinery::Core::Engine.routes.prepend do

  devise_for :clients,  :class_name => "Refinery::Clients::Client",
                                :controllers => {:sessions => 'refinery/clients/sessions', :passwords => 'refinery/clients/passwords', :registrations => 'refinery/clients/registrations', :confirmations => 'refinery/clients/confirmations'}

  devise_scope :client do
      get "/clients/change_psw", :to => "clients/registrations#edit_password", :as => :edit_password
      match 'raptcha(/:action)', to: 'clients/registrations#raptcha_generate'
  end

  get "/clients/office", :to => "clients/office#index", :as => :office

  namespace :clients do
    resources :ships, controller: 'ships'
    match 'uploadfile', to: 'upload#create_file', :as => :uploadfile, via: [:post]
    match 'uploadphoto', to: 'upload#create_photo', :as => :uploadphoto, via: [:post]
    match 'deletefile', to: 'upload#delete_file', :as => :deletefile, via: [:post]
    match 'deletephoto', to: 'upload#delete_photo', :as => :deletephoto, via: [:post]

    match 'subscribed', to: 'subscribe#subscribed', :as => :subscribed, via: [:post]
    match 'unsubscribed', to: 'subscribe#unsubscribed', :as => :unsubscribed, via: [:post]
  end
  match 'sendnewsmail/:id', to: 'news/items#send_news_to_subscribers', :as => :sendnewsmail

end

Refinery::Ships::Engine.routes.prepend do
  devise_for :clients,  :class_name => "Refinery::Clients::Client",
                                :controllers => {:office => 'refinery/clients/office', :sessions => 'refinery/clients/sessions', :passwords => 'refinery/clients/passwords', :registrations => 'refinery/clients/registrations', :confirmations => 'refinery/clients/confirmations'}
  devise_scope :client do
      get "/clients/office", :to => "clients/office#index", :as => :office
  end

  namespace :clients do
    resources :ships, controller: 'ships'
    match 'uploadfile', to: 'upload#create_file', :as => :uploadfile, via: [:post]
    match 'uploadphoto', to: 'upload#create_photo', :as => :uploadphoto, via: [:post]
    match 'deletefile', to: 'upload#delete_file', :as => :deletefile, via: [:post]
    match 'deletephoto', to: 'upload#delete_photo', :as => :deletephoto, via: [:post]
  end
end

Refinery::Inquiries::Engine.routes.prepend do
  devise_for :clients,  :class_name => "Refinery::Clients::Client",
                                :controllers => {:office => 'refinery/clients/office', :sessions => 'refinery/clients/sessions', :passwords => 'refinery/clients/passwords', :registrations => 'refinery/clients/registrations', :confirmations => 'refinery/clients/confirmations'}
  devise_scope :client do
      get "/clients/office", :to => "clients/office#index", :as => :office
  end
end

Refinery::News::Engine.routes.prepend do
  devise_for :clients,  :class_name => "Refinery::Clients::Client",
                                :controllers => {:office => 'refinery/clients/office', :sessions => 'refinery/clients/sessions', :passwords => 'refinery/clients/passwords', :registrations => 'refinery/clients/registrations', :confirmations => 'refinery/clients/confirmations'}
  devise_scope :client do
      get "/clients/office", :to => "clients/office#index", :as => :office
  end
end

Marinerus::Application.routes.draw do

  mount Refinery::Core::Engine, :at => '/'

end

app/models/refinery/clients/client.rb
#require 'active_record'
require 'devise'

module Refinery
  module Clients
    class Client < Refinery::Core::BaseModel
      self.table_name = 'refinery_clients'

      has_many :ships, :class_name => 'Refinery::Ships::Ship'
      has_many :attachments, :class_name => 'Refinery::Ships::Attachment'

      acts_as_indexed :fields => [:name]

     # validates :email, :presence => true, :uniqueness => true

      #devise methods
      # Include default devise modules. Others available are:
	# :token_authenticatable, :confirmable,
	# :lockable, :timeoutable and :omniauthable
      #attr_accessor :login
      devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :confirmable, :authentication_keys => [:email]

	# Setup accessible (or protected) attributes for your model
	attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :company, :job, :phone, :mail_me

    end
  end
end

app/controllers/refinery/clients/confirmations_controller.rb
module Refinery
  module Clients
    class ConfirmationsController < Devise::ConfirmationsController
      helper Refinery::Core::Engine.helpers
      # layout 'refinery/clients/layouts/login'
      # GET /resource/confirmation/new
      def new
        build_resource({})
      end

      # POST /resource/confirmation
      def create
        self.resource = resource_class.send_confirmation_instructions(resource_params)

        if successfully_sent?(resource)
          respond_with({}, :location => after_resending_confirmation_instructions_path_for(resource_name))
        else
          respond_with(resource)
        end
      end

      # GET /resource/confirmation?confirmation_token=abcdef
      def show
        self.resource = resource_class.confirm_by_token(params[:confirmation_token])

        if resource.errors.empty?
          logger.debug(resource)
          logger.debug(resource_name)
          set_flash_message(:notice, :confirmed) if is_navigational_format?
          # respond_with_navigational(resource){ redirect_to after_confirmation_path_for(resource_name, resource) }
          redirect_to office_path if sign_in(resource_name, resource)
          # all my stupied tries next:
          # respond_with_navigational(resource){ redirect_to office_path }
          # respond_with resource, :location => after_sign_in_path_for(resource)
        else
          respond_with_navigational(resource.errors, :status => :unprocessable_entity){ render :new }
        end
      end

      protected

        # The path used after resending confirmation instructions.
        def after_resending_confirmation_instructions_path_for(resource_name)
          new_session_path(resource_name) if is_navigational_format?
        end

        # The path used after confirmation.
        def after_confirmation_path_for(resource_name, resource)
          after_sign_in_path_for(resource)
        end
      
    end
  end
end

app/controllers/refinery/clients/office_controller.rb
module Refinery
  module Clients
    class OfficeController < ::ApplicationController
        layout 'refinery/clients/layouts/login'
        #before_filter :check, :only=>[:create]
        # crudify   :'refinery/ships/ship', 
            # :xhr_paging => true

        #before_filter :all_collections, :only=>[:new, :edit]

        def index
            if client_signed_in?
                @ships = Refinery::Ships::Ship.includes(:translations, :page_status).where(:client_id=>current_client.id).order('updated_at DESC')
                @all = @ships
                @moderate = @ships.select{|ship| ship.page_status.id == 1}
                @published = @ships.select{|ship| ship.page_status.id == 2}
                if (params[:status]=='1' or params[:status]=='2')
                    params[:status]=='1' ? @ships = @moderate : @ships = @published
                end
            else
                 redirect_to(root_path)
            end
        end
        

        protected
        def all_collections
            @categories = Refinery::Categories::Category.all
            #@clients

            @page_statuss = PageStatus.all
            @statuss = Status.all
            @areas = Area.all
            @choices = Choice.all
            @conditions = Condition.all
            @currencies = Currency.all
            @enginetypes = Enginetype.all
            @fuels = Fuel.all
            @gmdsss = Gmdss.all
            @hullmaterials = Hullmaterial.all
            @hulltypes = Hulltype.all
            @powers = Power.all
            @propulsions = Propulsion.all
            @registrations = Registration.all
            @registrs = Registr.all
            @speeds = Speedname.all
            @vats = Vat.all
        end

    end
  end
end

app/controllers/refinery/clients/passwords_controller.rb
module Refinery
  module Clients
    class PasswordsController < Devise::PasswordsController
    	layout 'refinery/clients/layouts/login'
    	# prepend_before_filter :log, :only => :update

    	  def edit
	    self.resource = resource_class.new
	    resource.reset_password_token = params[:reset_password_token]
	  end

	  # PUT /resource/password
	  def update
	    self.resource = resource_class.reset_password_by_token(resource_params)

	    if resource.errors.empty?
	      resource.unlock_access! if unlockable?(resource)
	      flash_message = resource.active_for_authentication? ? :updated : :updated_not_active
	      set_flash_message(:notice, flash_message) if is_navigational_format?
	      sign_in(resource_name, resource)
	      respond_with resource, :location => after_resetting_password_path_for(resource)
	    else
	      respond_with resource
	    end
	  end


	  protected
		def after_sending_reset_password_instructions_path_for(resource_name)
			office_path
		end
		def after_resetting_password_path_for(resource)
			office_path
		end
    end
  end
end

app/controllers/refinery/clients/sessions_controller.rb
module Refinery
  module Clients
    class SessionsController < Devise::SessionsController
    	layout 'refinery/clients/layouts/login'
    	#before_filter :check, :only=>[:create]

	def create
     		client = Client.find_by_email(params[:client][:email])
		if client.present? and client.valid_password?(params[:client][:password])
			self.resource = client
		else
			self.resource = warden.authenticate!(auth_options)
		end
		set_flash_message(:notice, :signed_in) if is_navigational_format?
		sign_in(resource_name, resource)
		respond_with resource, :location => after_sign_in_path_for(resource)
	end

      def create_default
        self.resource = warden.authenticate!(auth_options)
        set_flash_message(:notice, :signed_in) if is_navigational_format?
        sign_in(resource_name, resource)
        respond_with resource, :location => after_sign_in_path_for(resource)
      end

    	protected
    	def after_sign_in_path_for(resource_or_scope)
    		refinery.root_path
    	end
    	# def after_sign_out_path_for(resource_or_scope)
    	# 	refinery.root_path
    	# end

    # 	def auth_options
    #   { :default_scope => :client, :default_strategies => :client}
    # end

    def check
    	#request.env["devise.skip_timeout"] = true 
    	request.env["authentication_keys"] = [:email]

    	logger.debug("//////////////////////////////////////////////////////////")
    	logger.debug(">request.env:  #{lambda{request.env.each do |t| return t end}.call}")
    	logger.debug("//////////////////////////////////////////////////////////")
    	logger.debug(">>>>>>>>>>>>>>>>>>devise.skip_timeout:   #{request.env["devise.skip_timeout"]} >>class: devise.skip_timeout:   #{request.env.class}")
    	logger.debug(">>>>>>>>>>>>>>>>>>warden:   #{warden}>>class:   #{warden.class}")
    	logger.debug(">>>>>>>>>>>>>>>>>>warden:   #{request.env["authentication_keys"]}")
    	logger.debug(">>>>>>>>>>>>>>>>>>warden:   #{request.env["request_keys"]}")

    end
    	
    end
  end
end

app/controllers/refinery/clients/ships_controller.rb
module Refinery
  module Clients
    class ShipsController < ::ApplicationController #< ::ActionController::Base
      #include ::Refinery::ApplicationController
      #helper ApplicationHelper
      #helper Refinery::Core::Engine.helpers
      #include Refinery::Admin::BaseController
      layout 'refinery/clients/layouts/login'


    	before_filter :client?, except: :new
    	before_filter :add_new_client?, only: :new

      crudify	:'refinery/ships/ship',
      			:xhr_paging => true

      before_filter	:all_collections, :only=>[:new, :edit, :create, :update]
      before_filter	:new_attach_init, :only=>[:new]
      before_filter	:edit_attach_init, :only=>[:edit, :update]
      before_filter	:create_attach_init, :only=>[:create]
      # before_filter	:attach_update, :only=>[:create, :update]

      def new
        @ship = Refinery::Ships::Ship.new(:client_id=>current_client.id)
      end

      def create
      	@attach = Refinery::Ships::Attachment.where({client_id: current_client.id, ship_id: nil}).first
		if (@ship = Refinery::Ships::Ship.create(params[:ship]){|s| s.client_id = current_client.id}).valid?  #do |s| s.client_id = current_client.id end).valid?
			flash.notice = t(
			'refinery.crudify.created',
			:what => "#{@ship.title}'"
			)

                    attach_update
                    ::Refinery::Inquiries::InquiryMailer.order_notification(@ship).deliver
			redirect_to office_path
		else
			create_or_update_unsuccessful 'new'
		end
      end

      # def edit
      #   # object gets found by find_#{singular_name} function
      #   @attach = Refinery::Ships::Attachment.where(ship_id: @ship.id).first
      # end

      def update
	      if @ship.update_attributes(params[:ship])
			#attach_update
			redirect_to office_path
		else
			create_or_update_unsuccessful 'edit'
	      end
      end

      def destroy
		if @ship.destroy
			redirect_to office_path
		end
      end
#####################################----Set locale----#############################################################################
      def find_or_set_locale
        if (params[:set_locale] and ::Refinery::I18n.locales.keys.map(&:to_sym).include?(params[:set_locale].to_sym))
          ::Refinery::I18n.current_locale = params[:set_locale].to_sym
          redirect_back_or_default(refinery.admin_root_path) and return
        else
          ::I18n.locale = ::Refinery::I18n.current_locale
        end
      end

      def globalize!
        if ::Refinery::I18n.frontend_locales.any?
          if params[:switch_locale]
            Thread.current[:globalize_locale] = params[:switch_locale].to_sym
          elsif ::I18n.locale != ::Refinery::I18n.default_frontend_locale
            Thread.current[:globalize_locale] = ::Refinery::I18n.default_frontend_locale
          end
        end

        Thread.current[:globalize_locale] = ::I18n.locale if Thread.current[:globalize_locale].nil?
      end
      # globalize! should be prepended first so that it runs after find_or_set_locale
      prepend_before_filter :globalize!, :find_or_set_locale
      protected :globalize!, :find_or_set_locale
###################################################################################################################################
      protected
      def client?
      		redirect_to root_path if !client_signed_in?
      end
      def add_new_client?
      		redirect_to new_client_registration_path if !client_signed_in?
      end
      def all_collections
        @categories = Refinery::Categories::Category.all
        #@clients

        @page_statuss = Refinery::Ships::PageStatus.all
        @statuss = Refinery::Ships::Status.all
        @areas = Refinery::Ships::Area.all
        @choices = Refinery::Ships::Choice.all
        @conditions = Refinery::Ships::Condition.all
        @currencies = Refinery::Ships::Currency.all
        @enginetypes = Refinery::Ships::Enginetype.all
        @fuels = Refinery::Ships::Fuel.all
        @gmdsss = Refinery::Ships::Gmdss.all
        @hullmaterials = Refinery::Ships::Hullmaterial.all
        @hulltypes = Refinery::Ships::Hulltype.all
        @powers = Refinery::Ships::Power.all
        @propulsions = Refinery::Ships::Propulsion.all
        @registrations = Refinery::Ships::Registration.all
        @registrs = Refinery::Ships::Registr.all
        @speeds = Refinery::Ships::Speedname.all
        @fuelnames = Refinery::Ships::Fuelname.all
        @vats = Refinery::Ships::Vat.all
      end

      def new_attach_init
	      	if @attach = Refinery::Ships::Attachment.where({client_id: current_client.id, ship_id: nil}).first
	      		@attach.photos.each {|e| e.destroy} if @attach.photos.any? 
	      		@attach.docs.each {|e| e.destroy} if @attach.docs.any?
	      		@attach.reload
	      	else
	      		@attach = Refinery::Ships::Attachment.create(client_id: current_client.id)
	      	end
	      	@fileholder = Refinery::Ships::Doc.new
      		@photoholder = Refinery::Ships::Photo.new
      end
      
      def edit_attach_init
    		@attach = Refinery::Ships::Attachment.where(ship_id: @ship.id).first
    		#@attach = Refinery::Ships::Attachment.where({client_id: current_client.id, ship_id: params[:id]}).first
    		@fileholder = Refinery::Ships::Doc.new
    		@photoholder = Refinery::Ships::Photo.new
    	end

    	def create_attach_init
    		@attach = Refinery::Ships::Attachment.where({client_id: current_client.id, ship_id: nil}).first
    		@fileholder = Refinery::Ships::Doc.new
    		@photoholder = Refinery::Ships::Photo.new
    	end

      def attach_update
    		@attach.update_attributes(ship_id: @ship.id)
      end
    end
  end
end

app/controllers/refinery/clients/upload_controller.rb
module Refinery
	module Clients
		class UploadController < ::ApplicationController#::ActionController::Base 

			def create_file
				@fileholder = Refinery::Ships::Doc.create(params[:doc])
			end

			def create_photo
				@photoholder = Refinery::Ships::Photo.create(params[:photo])
			end

			def delete_photo
				@id = params[:id]
				@photoholder = Refinery::Ships::Photo.find(params[:id])
				@photoholder.photo = nil
				@photoholder.destroy

				render :text => "Deleted #{params[:id]}"
			end

			def delete_file
				@id = params[:id]
				@fileholder = Refinery::Ships::Doc.find(params[:id])
				@fileholder.doc = nil
				@fileholder.destroy

				render :text => "Deleted #{params[:id]}"
			end
		end
	end
end

app/views/refinery/clients/ships/BCP_new.html.erb
<div class="wrap">
	<%= render 'form' %>
	<div id="modalfile">
		<%= render 'add_file' %>
	</div>
</div>

app/views/refinery/clients/ships/_actions.html.erb
<ul>
  <% if ::Refinery::Ships::Admin::ShipsController.searchable? %>
    <li>
      <%= render '/refinery/admin/search', :url => refinery.ships_admin_ships_path %>
    </li>
  <% end %>
  <li>
    <%= link_to t('.create_new'), refinery.new_ships_admin_ship_path,
                 :class => "add_icon" %>
  </li>
<% if !searching? && ::Refinery::Ships::Admin::ShipsController.sortable? && ::Refinery::Ships::Ship.many? %>
  <li>
    <%= link_to t('.reorder', :what => "Ships"),
                 refinery.ships_admin_ships_path,
                 :id => "reorder_action",
                 :class => "reorder_icon" %>

    <%= link_to t('.reorder_done', :what => "Ships"),
                 refinery.ships_admin_ships_path,
                 :id => "reorder_action_done",
                 :style => "display: none;",
                 :class => "reorder_icon" %>
  </li>
<% end %>
</ul>

app/views/refinery/clients/ships/_add_file.html.erb
<div id="filemanager">
  <div class="filemanager">
  	<div class="closemanager">Закрыть</div>
  	<%= form_for @fileholder, url: clients_uploadfile_path, :html => { :multipart => true }, :remote => true do |form| %>
  	  <%= form.hidden_field :attachment_id, :value => @attach.id %>
  	  <%= form.label :doc, "Загрузить файлы", :class => "ajaxuploadlabel" %>
  	  <%= form.file_field :doc, :multiple => true, :name => "doc[doc]" , :style=>"display:none" %>
  	<% end %>
  	<ul id="fileprws">
  		<%= render "refinery/clients/upload/collectfileprw", attach: @attach if @attach.docs.any? %>
  	</ul>
  </div>
</div>

app/views/refinery/clients/ships/_add_photo.html.erb
<div id="photomanager">
  <div class="filemanager">
  	<div class="closemanager">Закрыть</div>
  	<%= form_for @photoholder, url: clients_uploadphoto_path, :html => { :multipart => true }, :remote => true do |form| %>
  	  <%= form.hidden_field :attachment_id, :value => @attach.id %>
  	  <%= form.label :photo, "Загрузить фото", :class => "ajaxuploadlabel" %>
  	  <%= form.file_field :photo, :multiple => true, :name => "photo[photo]" , :style=>"display:none" %>
  	<% end %>
  	<div id="photoprws">
  		<%= render "refinery/clients/upload/collectphotoprw", attach: @attach if @attach.photos.any? %>
  	</div>
  </div>
</div>

app/views/refinery/clients/ships/_records.html.erb
<%= render 'refinery/admin/search_header', :url => refinery.ships_admin_ships_path %>
<div class='pagination_container'>
  <% if @ships.any? %>
    <%= render 'ships' %>
  <% else %>
    <p>
      <% unless searching? %>
        <strong>
          <%= t('.no_items_yet') %>
        </strong>
      <% else %>
        <%= t('no_results', :scope => 'refinery.admin.search') %>
      <% end %>
    </p>
  <% end %>
</div>

app/views/refinery/clients/ships/_ship.html.erb
<li class='clearfix record <%= cycle("on", "on-hover") %>' id="<%= dom_id(ship) -%>">
  <span class='title'>
    <%= ship.title %>

    <% if Refinery::I18n.frontend_locales.many? %>
      <span class='preview'>
        <% ship.translations.each do |translation| %>
          <% if translation.title.present? %>
            <%= link_to refinery_icon_tag("flags/#{translation.locale}.png", :size => '16x11'),
                         refinery.edit_ships_admin_ship_path(ship, :switch_locale => translation.locale),
                         :class => 'locale' %>
          <% end %>
        <% end %>
      </span>
    <% end %>

  </span>
  <span class='actions'>
    
    <%= link_to refinery_icon_tag("application_go.png"), refinery.ships_ship_path(ship),
        :title => t('.view_live_html'),
        :target => "_blank" %>
    
    <%= link_to refinery_icon_tag("application_edit.png"), refinery.edit_ships_admin_ship_path(ship),
         :title => t('.edit') %>
    <%= link_to refinery_icon_tag("delete.png"), refinery.ships_admin_ship_path(ship),
        :class => "cancel confirm-delete",
        :title => t('.delete'),
        :confirm => t('message', :scope => 'refinery.admin.delete', :title => ship.title),
        :method => :delete %>
  </span>
</li>

app/views/refinery/clients/ships/_ships.html.erb
<%= will_paginate @ships if Refinery::Ships::Admin::ShipsController.pageable? %>
<%= render 'sortable_list' %>

app/views/refinery/clients/ships/_sortable_list.html.erb
<ul id='sortable_list'>
  <%= render :partial => 'ship', :collection => @ships %>
</ul>
<%= render '/refinery/admin/sortable_list',
            :continue_reordering => (local_assigns.keys.include?(:continue_reordering)) ? continue_reordering : true %>

app/views/refinery/clients/ships/edit.html.erb
<div class="wrap">
	<%= render 'add_file' %>
	<%= render 'add_photo' %>
	<%= render 'form' %>
</div>

app/views/refinery/clients/ships/index.html.erb
<section id='records'>
  <%= render 'records' %>
</section>
<aside id='actions'>
  <%= render 'actions' %>
</aside>
<%= render '/refinery/admin/make_sortable', :tree => false if !searching? and ::Refinery::Ships::Admin::ShipsController.sortable? and ::Refinery::Ships::Ship.many? %>

app/views/refinery/clients/ships/new.html.erb
<div class="wrap">
	<%= render 'add_file' %>
	<%= render 'add_photo' %>
	<%= render 'form' %>
</div>